name: Sync Data
on:
  schedule:
    - cron: '0 8 * * *'  # Ежедневно в 08:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install pandas sqlalchemy pymysql gspread google-auth
          
      - name: List files (debug)
        run: ls -R  # Покажет структуру файлов для отладки
          
      - name: Run sync script
        env:
          GDRIVE_CREDS: ${{ secrets.GDRIVE_CREDS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          # Убедитесь что имя файла точно совпадает
          python commission.py || python src/commission.py || python scripts/commission.py
