name: Sync Data
on:
  schedule:
    - cron: '0 8 * * *'  # Daily at 08:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-22.04  # Используем конкретную версию
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential

    - name: Clean Python environment
      run: |
        pip uninstall -y numpy pandas  # Очищаем возможные конфликтующие версии

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.23.5  # Специально подобранная стабильная версия
        pip install \
          pandas==1.5.3 \
          sqlalchemy==1.4.46 \
          pymysql==1.0.2 \
          google-api-python-client==2.104.0 \
          google-auth-httplib2==0.1.0 \
          google-auth-oauthlib==0.8.0 \
          pyopenssl==23.2.0

    - name: Verify installations
      run: |
        python -c "import numpy as np; print(f'numpy: {np.__version__}')"
        python -c "import pandas as pd; print(f'pandas: {pd.__version__}')"

    - name: Run sync script
      env:
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        GDRIVE_CREDS: ${{ secrets.GDRIVE_CREDS }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        python commision.py
