name: Sync Data
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install pandas==2.0.3 sqlalchemy==2.0.19 pymysql==1.1.0 
          pip install gspread==5.11.0 google-auth==2.22.0
          
      - name: Verify files
        run: |
          ls -la
          [ -f "commision.py" ] && echo "File exists" || echo "File missing"
          
      - name: Run sync script
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_CREDS: ${{ secrets.GDRIVE_CREDS }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: python commision.py
