name: Sync Data
on:
  schedule:
    - cron: '0 8 * * *'  # Daily at 08:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libpq-dev

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install --force-reinstall numpy==1.24.4
        pip install \
          pandas==2.0.3 \
          sqlalchemy==2.0.19 \
          pymysql==1.1.0 \
          gspread==5.11.0 \
          google-auth==2.22.0 \
          pyopenssl==23.2.0

    - name: Verify installations
      run: |
        python -c "import numpy as np; print(f'numpy version: {np.__version__}')"
        python -c "import pandas as pd; print(f'pandas version: {pd.__version__}')"

    - name: Run sync script
      env:
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        GDRIVE_CREDS: ${{ secrets.GDRIVE_CREDS }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        python commision.py
